### GENERAL SETTINGS ###

title: Martche House
co_name: Martche House

analytics:

baseurl: ""
url: "https://mmartche.ca"

markdown: kramdown

permalink: /:categories/:title

excerpt_separator: "<!--more-->"

plugins:
  - jekyll-multiple-languages-plugin

languages:
  - pt
  - en

exclude_from_localizations:
  - assets

default_locale_in_subfolder: false

colors:
  primary: "darkslategray"
  primary_rgb: "0,100,0"
  secondary: "#020210"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

social:
  - title: twitter
    url: "https://twitter.com/"


address:
  - lines:
      - "No momento a nossa equipe está alocada remotamente."
      - "Usamos algumas startups para locação de salas de reunião em todo o país caso necessário, assim tornando mais flexível para a equipe técnica e o cliente."
      - ""
      - "email: mmartche@hotmail.com"


### GENERAL DATA ###

about: "Somos uma empresa focada em consultoria e serviços voltados a Open Source."

about2: "Somos mais do que profissionais porque fazemos o que gostamos, de coração. Agindo no ponto certo onde é vital."

google-site-verification: ""

sitemap:
  file: "/sitemap2.xml"

  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"

  include_posts:
    - "/index.html"