services:
  jekyll:
    build: .
    container_name: martche-house
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    command: >
      bundle exec jekyll serve
      --host 0.0.0.0
      --livereload
      --force_polling

volumes:
  bundle_cache: